#!/usr/bin/env python

import sys,subprocess,time

ival = int(sys.argv[1]) - 1

nd = int(sys.argv[2])

dp = int(sys.argv[3])

all = sys.stdin.readlines()
num = all[ival]
num = num[:-1]

cur_num = num[0:nd+2]

print "%4d %6d " % (dp,nd),
command = "echo 'algdep(%s,%d)' | gp -s 1000000000 | grep '%%1'" % (cur_num,dp)
ts = time.time()
output = subprocess.check_output(command,shell=True)
te = time.time()
parts = output.split()
print "%10.3le" % (te-ts)," ",output
sys.stdout.flush()
