#!/usr/bin/env python

import sys,subprocess,time

ival = int(sys.argv[1]) - 1

nds = int(sys.argv[2])
nde = int(sys.argv[3])
ndr = int(sys.argv[4])

ndl = []
nd = nds
while nd <= nde:
  ndl.append(nd)
  nd += ndr

dps = int(sys.argv[5])
dpe = int(sys.argv[6])
dpr = int(sys.argv[7])

dpl = []
dp = dps
while dp <= dpe:
  dpl.append(dp)
  dp += dpr

all = sys.stdin.readlines()
num = all[ival]
num = num[:-1]

for dp in dpl:
  for nd in ndl:
    cur_num = num[0:nd+2]

    print "%4d %6d " % (dp,nd),
    command = "echo 'algdep(%s,%d)' | gp -s 1000000000 | grep '%%1'" % (cur_num,dp)
    ts = time.time()
    output = subprocess.check_output(command,shell=True)
    te = time.time()
    parts = output.split()
    print "%10.3le" % (te-ts)," ",parts[2]," ",parts[-1]
    sys.stdout.flush()
  print
  sys.stdout.flush()
