#!/bin/csh -f
set REPORT = 50
set SAVE   = 100
set TRIES  = 100
set RATE   = 0.021604884327801591229336142377946275
set argc = $#argv
set curline = 1
if ($argc >= 1) then
    set curline = $1
endif
set maxline = `cat runsome.list | wc -l`
# /bin/rm -f runsome.results
while ($curline <= $maxline)
  set ccurline = `echo $curline | awk '{printf("%03d",$1);}'`
  set values = `/usr/bin/tail --lines=+$curline runsome.list | head -1`
  set indim = $values[1]
  set outdim = $values[2]
  set multi = $values[3]
  set SREPORT = `echo $REPORT $multi | awk '{printf("%d",$1*$2);}'`
  set SSAVE   = `echo $SAVE   $multi | awk '{printf("%d",$1*$2);}'`
  set STRIES  = `echo $TRIES  $multi | awk '{printf("%d",$1*$2);}'`
  set SRATE   = `echo $RATE   $multi | awk '{printf("%33.31f",$1/$2);}'`
  set lines = `echo "3 + ($outdim + 1)" | /usr/bin/bc`
  set ext = `echo $indim $outdim | awk '{ printf("%03d.%03d",$1,$2); }'`
  echo $indim $outdim
  sed -e "s/OUTDIM/$outdim/"      \
      -e "s/INDIM/$indim/"        \
      -e "s/REPORT/$SREPORT/"     \
      -e "s/SAVE/$SSAVE/"         \
      -e "s/TRIES/$STRIES/"       \
      -e "s/RATE/$SRATE/"         \
      < runsome.param > runsome.temp
  echo "$indim $outdim" | awk '{ printf("%3d %3d    ",$1,$2); }' >>! runsome.results
  (./cube -p runsome.temp | tail -$lines > runsome.vertices/run.$ext) |& tee runsome.stats
  awk 'NF == 4 { side = -$3; } \
       END { printf("%20.17f\n",side); }' < runsome.stats \
       >>! runsome.results
  /bin/mv runsome.stats runsome.$ccurline.stats
  echo ""

  @ curline++
end
