#!/usr/bin/env python

import sys
import list_io

file = sys.stdin
if len(sys.argv) > 1:
  file = open(sys.argv[1],"r")

list_key = list_io.read_key(file)
(maxm,maxn,list_pairs) = list_io.read_body(file)

file.close()

list_key["a"] = ("provable",)

m = 1
for n in xrange(1,maxn+1):
  if (m,n) in list_pairs:
    list_pairs[(m,n)].add("a")

m = 2
for n in xrange(2,maxn+1):
  if (m,n) in list_pairs:
    list_pairs[(m,n)].add("a")

for n in xrange(1,maxn+1):
  m = n
  if (m,n) in list_pairs:
    list_pairs[(m,n)].add("a")

list_pairs[(3,4)].add("a")

file = sys.stdout
if len(sys.argv) > 1:
  file = open(sys.argv[1],"w")

list_io.write_key(list_key,file)
list_io.write_body(maxm,maxn,list_pairs,file)
