#!/usr/bin/env python

import sys

maxn = 100
maxm = 0 

if len(sys.argv) > 1:
  maxn = int(sys.argv[1])
  if len(sys.argv) > 2:
    maxm = int(sys.argv[2])

if maxm == 0:
  maxm = maxn/2

print
for n in xrange(1,maxn+1):
  for m in xrange(1,min(n+1,maxm+1)):
    print "%3d %3d " % (m,n)
  print
